title = "Josh's Blog"

[author]
name = "Joshua Lopes"
image = "pfp.png"
headline = "Web developer"
bio = "Student from the UK"
links = [
  { github = "https://github.com/joshua861" },
  { email = "mailto:joshrl@proton.me" },
  { twitter = "https://twitter.com/l71388196"},
  { youtube = "https://www.youtube.com/channel/UCCKUNCQcOApKqYZG5on-D0w"}
]
