name = "Holy"
license = "MIT"
licenselink = "https://github.com/serkodev/holy/blob/master/LICENSE"
description = "A simple and clean Hugo theme"
homepage = "https://github.com/serkodev/holy"
demosite = "https://hugo-holy.pages.dev/"
tags = ["blog", "responsive", "simple", "minimal", "personal", "dark", "dark mode", "contact"]
features = ["fast", "blog", "syntax highlighting", "dark mode"]
min_version = "0.41.0"

[author]
  name = "SerKo"
  homepage = "https://serko.dev"
